# golangci-lint configuration
# https://golangci-lint.run/usage/configuration/

version: "2"

run:
  timeout: 5m
  tests: false  # Don't lint test files

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - revive
    - gosec
    - bodyclose
    - noctx
    - unconvert
    - unparam
    - whitespace
    - gocyclo
    - gocognit
    - dupl
    - goconst
    - goprintffuncname
    - errorlint
    - nilerr
    - predeclared

  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true

    govet:
      enable-all: true
      disable:
        - shadow
        - fieldalignment

    gocyclo:
      min-complexity: 15

    gocognit:
      min-complexity: 20

    dupl:
      threshold: 100

    goconst:
      min-len: 3
      min-occurrences: 3

    misspell:
      locale: US

    revive:
      rules:
        - name: package-comments
          disabled: true  # Not required
        - name: unused-parameter
          disabled: true  # Cobra requires all params

    gosec:
      severity: medium
      confidence: medium
      excludes:
        - G104

    staticcheck:
      checks: ["all", "-ST1000"]

formatters:
  enable:
    - gofmt
    - goimports
