package nginx

// StreamTemplate is the Nginx stream module configuration template
// Generates TCP and UDP proxy server blocks with upstream definitions
const StreamTemplate = `# Auto-generated by proxy-nginx at {{.Timestamp}}
# DO NOT EDIT MANUALLY - Changes will be overwritten

{{range .Containers}}
{{if or .TCPMappings .UDPMappings}}
# Container: {{.Name}} ({{.ID}})
{{range .TCPMappings}}
upstream tcp_{{.ProxyPort}} {
    server {{.ContainerIP}}:{{.ContainerPort}};
}

server {
    listen {{.ProxyPort}};
    proxy_pass tcp_{{.ProxyPort}};
    proxy_connect_timeout 10s;
    proxy_timeout 5m;
    proxy_buffer_size 16k;
}
{{end}}
{{range .UDPMappings}}
upstream udp_{{.ProxyPort}} {
    server {{.ContainerIP}}:{{.ContainerPort}};
}

server {
    listen {{.ProxyPort}} udp;
    proxy_pass udp_{{.ProxyPort}};
    proxy_timeout 30s;
    proxy_responses 1;
    proxy_buffer_size 16k;
}
{{end}}
{{end}}
{{end}}
`

// HTTPTemplate is the Nginx HTTP module configuration template
// Generates HTTP server blocks with hostname-based routing and proxy headers
const HTTPTemplate = `# Auto-generated by proxy-nginx at {{.Timestamp}}
# DO NOT EDIT MANUALLY - Changes will be overwritten

{{range .HTTPServers}}
# Container: {{.ContainerName}} ({{.ContainerID}})
upstream {{.UpstreamName}} {
    server {{.ContainerIP}}:{{.ContainerPort}};
}

server {
    listen {{if .HTTPS}}443 ssl{{else}}80{{end}};
    server_name {{.Hostname}};

    location / {
        proxy_pass http://{{.UpstreamName}};

        # Proxy headers
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # WebSocket support
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        # Timeouts
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }
}
{{end}}
`
